export { default as Home } from "./Home.jsx";
export { default as LocalLoan } from "./LocalLoan.jsx";
export { default as CorporateProfile } from "./CorporateProfile.jsx";
export { default as GlobalLoan } from "./GlobalLoan.jsx";
export { default as RevolutionCommunity } from "./RevolutionCommunity.jsx";
export { default as WemaBank } from "./Banks/Wema.jsx";
export { default as Ecobank } from "./Banks/Ecobank.jsx";
export { default as UnionBank } from "./Banks/Union.jsx";
export { default as Sycamore } from "./Banks/Sycamore.jsx";
